FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

# Copia e instala dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código da aplicação
COPY . .

# Expõe a porta do Streamlit
EXPOSE 8501

# Comando para iniciar o dashboard
CMD ["streamlit", "run", "api/dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501", "--server.headless=true"]
